name: mops test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: ZenVoich/setup-mops@v1

      - name: make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: Show mops version
        run: mops -v

      - name: Install all mops dependencies
        run: mops install

      - name: run tests
        run: mops test --mode wasi
