name: Tests and formatting

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: ZenVoich/setup-mops@v1

      - name: make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: Show mops version
        run: mops -v

      - name: Install all mops dependencies
        run: mops install

      - name: run tests
        run: mops test --mode wasi

  format:
    name: Check formatting
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: "20"

      - name: Install prettier plugin
        run: npm install --save-dev prettier prettier-plugin-motoko

      - name: Run prettier check
        run: npx prettier --check --plugin=prettier-plugin-motoko **/*.mo
